---@brief [[
--- Extends sql object to have a customize db object without much work.
--- Example:
--- local manager = sql:extend {
---   uri = "~/.mytasks",
---   projects = {
---     id = true,
---     title = "string",
---     objectives = "luatable",
---   },
---   todos = {
---     id = true,
---     title = "string",
---     client = "number",
---     status = "string",
---     completed = "boolean",
---     details = "string",
---   },
---   opts = {
---     foreign_keys = true,
---   },
--- }
---@brief ]]
---@tag your_module
